### ISSUE TITLE
Something incorrect in the README.md

### ISSUE THREAD

**Issue by TommyGong08** [Sharpiless/MPI-Flow#1]
Hi, thanks for this good job. 
It seems that the link to the paper is wrong.
![image](https://github.com/Sharpiless/MPI-Flow/assets/56687665/14fa3161-e606-444e-ba24-30e250eaa51f)

Besides, the title in the citation seems to be another work.
![image](https://github.com/Sharpiless/MPI-Flow/assets/56687665/114b52ca-502a-408f-b874-295d58b9ef56)

**Comment by Sharpiless** [comment]
Thanks! Our paper has been submitted to arxiv and is still under review. We will  correct the title of the paper in the citation.
