### ISSUE TITLE
Files in output folder into zoom video

### ISSUE THREAD

**Issue by C00reNUT** [Sharpiless/MPI-Flow#3]
Hello, 

may I ask you how is it possible to convert files in output folder into zoom video as seen in examples in provided page?

**Comment by Sharpiless** [comment]
Hi, sorry for late. Thanks for your interest! You can follow the code of swing camera motions provided in [https://github.com/yxuhan/AdaMPI/blob/125f7c23315afe8f33f7b799d7bfcc66a9990ab4/utils/utils.py#L73](https://github.com/yxuhan/AdaMPI/blob/125f7c23315afe8f33f7b799d7bfcc66a9990ab4/utils/utils.py#L73) to generate continuous images and optical flows.
